import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "About Codevolution",
  description: "Generated by create next app",
};


export default function About() {
  return (
    <div>about</div>
  )
}
